import React from 'react';
import {View, Text, StyleSheet, ScrollView} from 'react-native';

const TermsConditions = () => {
  return (
    <>
      <ScrollView style={styles.scroll}>
        <View style={styles.container}>
          {/* ====== TERMS START ====== */}
          <View style={styles.div}>
            <Text style={styles.heading}>Terms</Text>
            <Text style={styles.para}>
              This document is an electronic record in terms of the amended
              Information Technology Act, 2000 and rules and regulation made
              thereunder. This electronic record is generated by a computer
              system and does not require any physical or digital signatures.
              This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              Guidelines) Rules, 2011 that require publishing the Terms for
              access or usage of Gizmmo Alchemy via Pantryo Apps. This document
              meets the stipulations and conditions mentioned in Section 65B (2)
              of the Indian Evidence Act, 1872.
            </Text>
            <Text style={styles.para}>
              This is an agreement between Gizmmo Alchemy, a company
              incorporated under the Companies Act 1956 with its registered
              office at A-23, Sector - J, Aliganj. Lucknow, the owner and
              operator of www.pantryo.com (the "Pantryo Website"), the Pantryo
              Application Software "Pantryo", including collectively, including
              all content provided by Pantryo through Pantryo Application and
              the Pantryo Site, the "Pantryo Service", or the "Service", and you
              ("you" or "You"), a user of the Service. BY USING THE SERVICE, YOU
              ACKNOWLEDGE AND AGREE TO THESE TERMS OF SERVICE, TERMS OF USE FOR
              SEARCH SERVICES, INFRINGEMENT POLICY, TERMS FOR UPI, SOFTWARE
              LICENSE AGREEMENT,SOFTWARE LICENSE AND PANTRYO'S PRIVACY POLICY,
              WHICH CAN BE FOUND AT PRIVACY POLICY AND WHICH ARE INCORPORATED
              HEREIN BY REFERENCE. If you choose to not agree with any of these
              terms, you may not use the Service.
            </Text>
          </View>
          {/* ====== TERMS END ====== */}

          {/* ====== PANTRYO SERVICE START ====== */}
          <View style={styles.div}>
            <Text style={styles.heading}>Pantryo Service</Text>
            <Text style={styles.para}>
              These Terms of Service apply to all users of Pantryo Platform.
              Information provided by our users through the Pantryo Platform may
              contain links to third party websites that are not owned or
              controlled by Pantryo. Pantryo has no control over, and assumes no
              responsibility for, the content, privacy policies, or practices of
              any third party websites. Also, Pantryo does not assume any
              liability for any mistakes, misstatements of law, defamation,
              omissions, falsehood, obscenity, pornography or profanity in the
              statements, opinions, representations or any other form of third
              party content on the Site. In addition, Pantryo will not and
              cannot censor or edit the content of any third-party site. By
              using the Service, you expressly acknowledge and agree that
              Pantryo shall not be responsible for any damages, claims or other
              liability arising from or related to your use of any third-party
              website. You understand that the information and opinions in the
              third party content represent solely the thoughts of the author
              and is neither endorsed by nor does it necessarily reflect
              Pantryo's belief.
            </Text>
          </View>
          {/* ====== PANTRYO SERVICE END ====== */}

          {/* ====== Errors, Corrections, and Right to Modify or Discontinue Service and Sites START ====== */}
          <View style={styles.div}>
            <Text style={styles.heading}>
              Errors, Corrections, and Right to Modify or Discontinue Service
              and Sites
            </Text>
            <Text style={styles.para}>
              We do not represent or warrant that the Pantryo Platform will be
              error-free, free of viruses or other harmful components, or that
              defects will be corrected. We do not represent or warrant that the
              information available on or through the Pantryo Platform will be
              correct, accurate, timely or otherwise reliable. We may make
              changes to the features, functionality or content of the Pantryo
              Platform at any time. We reserve the right in our sole discretion
              to edit or delete any documents, information or other content
              appearing on the Pantryo Platform. Pantryo reserves the right at
              any time and from time to time to modify or discontinue,
              temporarily or permanently, the Services and/or Sites (or any part
              thereof) with or without notice. Pantryo shall not be liable to
              you or to any third party for any modification, suspension or
              discontinuance of the Service or any Sites.
            </Text>
          </View>
          {/* ====== Errors, Corrections, and Right to Modify or Discontinue Service and Sites END ====== */}

          {/* ====== Pantryo Platform Access START ====== */}
          <View style={styles.div}>
            <Text style={styles.heading}>Pantryo Platform Access</Text>
            <Text style={styles.mainPoint}>
              A) Subject to your compliance with these Terms of Service, Pantryo
              hereby grants you permission to use the Service, provided that:
            </Text>
            <Text style={styles.subPoint}>
              1. Your use of the Service as permitted is solely for your
              personal use, and you are not permitted to resell or charge others
              for use of or access to the Service, or in any other manner
              inconsistent with these Terms of Service;
            </Text>
            <Text style={styles.subPoint}>
              2. You will not duplicate, transfer, give access to, copy or
              distribute any part of the Service in any medium without Pantryo's
              prior written authorization;
            </Text>
            <Text style={styles.subPoint}>
              3. You will not attempt to reverse engineer, alter or modify any
              part of the Service;
            </Text>
            <Text style={styles.subPoint}>
              4. You will otherwise comply with the terms and conditions of
              these Terms of Service and Privacy Policy. The Application is
              currently made available to you free of charge for your personal,
              non-commercial use. Pantryo reserves the right to amend or
              withdraw the Application, or charge for the application or service
              provided to you in accordance with these Pantryo Mobile App terms,
              at any time and for any reason.
            </Text>

            <Text style={styles.mainPoint}>
              B. In order to access and use the features of the Service, you
              acknowledge and agree that you will have to provide Pantryo with
              your mobile phone number. You expressly acknowledge and agree that
              in order to provide the Service, Pantryo may periodically access
              your contact list and/or address book on your mobile device to
              find and keep track of mobile phone numbers of other users of the
              Service. When providing your mobile phone number, you must provide
              accurate and complete information. You hereby give your express
              consent to Pantryo to access your contact list and/or address book
              for mobile phone numbers in order to provide and use the Service.
              You must notify Pantryo immediately of any breach of security or
              unauthorized use of your mobile phone. For removal of doubts it is
              clarified that, Pantryo is not liable for any loss or damage
              caused by any unauthorized use of your account, however you would
              be liable for any losses or damage caused to Pantryo Platform
              including but not limited to any claims made on Pantryo or others
              due to such unauthorized use.
            </Text>

            <Text style={styles.mainPoint}>
              C. You agree not to use or upload, post or submit any content that
              contains software viruses or any computer code, files, or programs
              designed to interrupt, destroy, or limit functionality of the
              Platform or of any computer software, hardware, or
              telecommunications equipment. You also agree to not decipher,
              decompile, disassemble, use sniffers (except Ethereal, tcpdump or
              HTTPWatch in general) or reverse engineer any of the software
              comprising or in any way making up part of the Pantryo Platform.
              We have to disallow use of request modification tools such as
              fiddler or whisker, or the like or any other such tools activities
              that are meant to explore or harm, penetrate or test the
              application. You must secure our permission before you measure,
              test, health check or otherwise monitor any network equipment,
              servers or assets hosted on our domain. You agree not to collect
              or harvest any personally identifiable information, including
              phone number, from the Service, nor to use the communication
              systems provided by the Service for any commercial solicitation or
              spam purposes. You agree not to spam, or solicit for commercial
              purposes, any users of the Service. You agree not to create any
              data back up of the content that is available to you by use of the
              Pantryo Platform or Pantryo Mobile App. or use of Pantryo Platform
              that is available through any other mediums.
            </Text>
          </View>
          {/* ====== Pantryo Platform Access END ====== */}
        </View>
      </ScrollView>
    </>
  );
};

export default TermsConditions;

const styles = StyleSheet.create({
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: '#ffffff',
    paddingTop: 10,
  },
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  div: {
    width: '100%',
    marginBottom: 10,
  },
  heading: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    color: '#5E3360',
    marginBottom: 5,
  },
  para: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'justify',
  },
  mainPoint: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    textAlign: 'justify',
  },
  subPoint: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginTop: 5,
    marginLeft: 10,
    marginBottom: 10,
    textAlign: 'justify',
  },
});
